# Generated by Django 5.0.6 on 2024-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_categories_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
