# Generated by Django 5.0.6 on 2024-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_last_post_date_userprofile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posted_today',
            field=models.BooleanField(default=False),
        ),
    ]
